In [1]:
import pandas as pd
import numpy as np

In [2]:
movies = pd.read_csv('./movielens/movies_all.csv')

In [3]:
movies = movies.drop('Unnamed: 0', axis=1)

In [4]:
movies.head(20)

,movieId,title,year,genres,n_users,rating_mean,rating_std
0,1,Toy Story,1995,Adventure|Animation|Children|Comedy|Fantasy,49695,3.921240,0.889012
1,2,Jumanji,1995,Adventure|Children|Fantasy,22243,3.211977,0.951150
2,3,Grumpier Old Men,1995,Comedy|Romance,12735,3.151040,1.006642
3,4,Waiting to Exhale,1995,Comedy|Drama|Romance,2756,2.861393,1.095702
4,5,Father of the Bride Part II,1995,Comedy,12161,3.064592,0.982140
5,6,Heat,1995,Action|Crime|Thriller,23899,3.834930,0.880468
6,7,Sabrina,1995,Comedy|Romance,12961,3.366484,0.955883
7,8,Tom and Huck,1995,Adventure|Children,1415,3.142049,0.966353
8,9,Sudden Death,1995,Action,3960,3.004924,0.960203
9,10,GoldenEye,1995,Action|Adventure|Thriller,29005,3.430029,0.859035
10,11,"American President, The",1995,Comedy|Drama|Romance,18162,3.667713,0.895807
11,12,Dracula: Dead and Loving It,1995,Comedy|Horror,3845,2.619766,1.123326
12,13,Balto,1995,Adventure|Animation|Children,1461,3.272416,0.980312
13,14,Nixon,1995,Drama,6022,3.432082,0.940845
14,15,Cutthroat Island,1995,Action|Adventure|Romance,2910,2.721993,1.084532
15,16,Casino,1995,Crime|Drama,17394,3.787455,0.863681
16,17,Sense and Sensibility,1995,Drama|Romance,20667,3.968573,0.951585
17,18,Four Rooms,1995,Comedy,5203,3.373631,1.029240
18,19,Ace Ventura: When Nature Calls,1995,Comedy,20938,2.607412,1.151479
19,20,Money Train,1995,Action|Comedy|Crime|Drama|Thriller,4084,2.880754,0.930137

In [158]:
(movies['n_users']==0).any()

True

In [100]:
movies.iloc[29]['title']

'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)'

In [135]:
title_new = list()
year = list()

In [136]:
for index, row in movies.iterrows():
    title = row['title']
    pat = 0
    for i in range(len(title)-1):
        if ( (title[i]=='(') & (title[i+1].isdigit()) ):
            pat = i
            break
    year.append(row['title'][pat+1:])
    title_new.append(row.loc['title'][:pat-1])

In [137]:
title_new = pd.Series(title_new)
year = pd.Series(year)
title_new

0                                                Toy Story
1                                                  Jumanji
2                                         Grumpier Old Men
3                                        Waiting to Exhale
4                              Father of the Bride Part II
5                                                     Heat
6                                                  Sabrina
7                                             Tom and Huck
8                                             Sudden Death
9                                                GoldenEye
10                                 American President, The
11                             Dracula: Dead and Loving It
12                                                   Balto
13                                                   Nixon
14                                        Cutthroat Island
15                                                  Casino
16                                   Sense and Sensibility
17                                              Four Rooms
18                          Ace Ventura: When Nature Calls
19                                             Money Train
20                                              Get Shorty
21                                                 Copycat
22                                               Assassins
23                                                  Powder
24                                       Leaving Las Vegas
25                                                 Othello
26                                            Now and Then
27                                              Persuasion
28       City of Lost Children, The (Cité des enfants p...
29           Shanghai Triad (Yao a yao yao dao waipo qiao)
                               ...
27248                               Werner - Volles Rooäää
27249                                           What A Man
27250                  7 Dwarves: The Forest Is Not Enough
27251                                          The Fat Spy
27252       Die Bademeister – Weiber, saufen, Leben retten
27253                                  Ants in the Pants 2
27254                                         Manta, Manta
27255                           Oscar and the Lady in Pink
27256                               Por un puñado de besos
27257                                        Vietnam in HD
27258                                           WWII IN HD
27259                                              Phoenix
27260                                            Parallels
27261                                       Closed Curtain
27262                                            Gentlemen
27263                                      A Second Chance
27264                              Dead Rising: Watchtower
27265                                              Standby
27266                                  What Men Talk About
27267                                   Three Quarter Moon
27268                                    Ants in the Pants
27269                         Werner - Gekotzt wird später
27270                                       Brother Bear 2
27271                                       No More School
27272      Forklift Driver Klaus: The First Day on the Job
27273                                Kein Bund für's Leben
27274                               Feuer, Eis & Dosenbier
27275                                          The Pirates
27276                                         Rentun Ruusu
27277                                            Innocence
Length: 27278, dtype: object

In [138]:
movies = pd.concat(axis=1,objs=[movies, title_new, year])

In [139]:
movies.tail(30)

,movieId,title,genres,n_users,rating_mean,rating_std,0,1
27248,131146,Werner - Volles Rooäää (1999),Animation|Comedy,1,4.0,0.0,Werner - Volles Rooäää,1999)
27249,131148,What A Man (2011),Comedy|Romance,1,4.0,0.0,What A Man,2011)
27250,131150,7 Dwarves: The Forest Is Not Enough (2006),Comedy,1,4.0,0.0,7 Dwarves: The Forest Is Not Enough,2006)
27251,131152,The Fat Spy (1966),Comedy,1,0.5,0.0,The Fat Spy,1966)
27252,131154,"Die Bademeister – Weiber, saufen, Leben retten...",Comedy,1,3.5,0.0,"Die Bademeister – Weiber, saufen, Leben retten",1999)
27253,131156,Ants in the Pants 2 (2002),Comedy,1,4.0,0.0,Ants in the Pants 2,2002)
27254,131158,"Manta, Manta (1991)",Comedy,2,4.0,0.0,"Manta, Manta",1991)
27255,131160,Oscar and the Lady in Pink (2009),Drama,1,4.0,0.0,Oscar and the Lady in Pink,2009)
27256,131162,Por un puñado de besos (2014),Drama|Romance,1,2.0,0.0,Por un puñado de besos,2014)
27257,131164,Vietnam in HD (2011),War,1,4.0,0.0,Vietnam in HD,2011)
27258,131166,WWII IN HD (2009),(no genres listed),1,4.0,0.0,WWII IN HD,2009)
27259,131168,Phoenix (2014),Drama,1,3.5,0.0,Phoenix,2014)
27260,131170,Parallels (2015),Sci-Fi,1,3.5,0.0,Parallels,2015)
27261,131172,Closed Curtain (2013),(no genres listed),1,1.0,0.0,Closed Curtain,2013)
27262,131174,Gentlemen (2014),Drama|Romance|Thriller,1,3.5,0.0,Gentlemen,2014)
27263,131176,A Second Chance (2014),Drama,1,4.5,0.0,A Second Chance,2014)
27264,131180,Dead Rising: Watchtower (2015),Action|Horror|Thriller,1,2.5,0.0,Dead Rising: Watchtower,2015)
27265,131231,Standby (2014),Comedy|Romance,1,3.5,0.0,Standby,2014)
27266,131237,What Men Talk About (2010),Comedy,1,3.0,0.0,What Men Talk About,2010)
27267,131239,Three Quarter Moon (2011),Comedy|Drama,1,4.0,0.0,Three Quarter Moon,2011)
27268,131241,Ants in the Pants (2000),Comedy|Romance,1,4.0,0.0,Ants in the Pants,2000)
27269,131243,Werner - Gekotzt wird später (2003),Animation|Comedy,1,4.0,0.0,Werner - Gekotzt wird später,2003)
27270,131248,Brother Bear 2 (2006),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,0.0,Brother Bear 2,2006)
27271,131250,No More School (2000),Comedy,1,4.0,0.0,No More School,2000)
27272,131252,Forklift Driver Klaus: The First Day on the Jo...,Comedy|Horror,1,4.0,0.0,Forklift Driver Klaus: The First Day on the Job,2001)
27273,131254,Kein Bund für's Leben (2007),Comedy,1,4.0,0.0,Kein Bund für's Leben,2007)
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,1,4.0,0.0,"Feuer, Eis & Dosenbier",2002)
27275,131258,The Pirates (2014),Adventure,1,2.5,0.0,The Pirates,2014)
27276,131260,Rentun Ruusu (2001),(no genres listed),1,3.0,0.0,Rentun Ruusu,2001)
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,1,4.0,0.0,Innocence,2014)

In [142]:
movies = movies.drop('title', axis=1)

In [150]:
movies = movies.rename(columns={0:'title', 1:'year'})

In [155]:
order = ['movieId','title','year','genres','n_users','rating_mean','rating_std']
movies = movies[order]

In [163]:
movies['year'] = movies['year'].apply(lambda x: x[:len(x)-1])

In [181]:
movies.head(15)

,movieId,title,year,genres,n_users,rating_mean,rating_std
0,1,Toy Story,1995,Adventure|Animation|Children|Comedy|Fantasy,49695,3.921240,0.889012
1,2,Jumanji,1995,Adventure|Children|Fantasy,22243,3.211977,0.951150
2,3,Grumpier Old Men,1995,Comedy|Romance,12735,3.151040,1.006642
3,4,Waiting to Exhale,1995,Comedy|Drama|Romance,2756,2.861393,1.095702
4,5,Father of the Bride Part II,1995,Comedy,12161,3.064592,0.982140
5,6,Heat,1995,Action|Crime|Thriller,23899,3.834930,0.880468
6,7,Sabrina,1995,Comedy|Romance,12961,3.366484,0.955883
7,8,Tom and Huck,1995,Adventure|Children,1415,3.142049,0.966353
8,9,Sudden Death,1995,Action,3960,3.004924,0.960203
9,10,GoldenEye,1995,Action|Adventure|Thriller,29005,3.430029,0.859035
10,11,"American President, The",1995,Comedy|Drama|Romance,18162,3.667713,0.895807
11,12,Dracula: Dead and Loving It,1995,Comedy|Horror,3845,2.619766,1.123326
12,13,Balto,1995,Adventure|Animation|Children,1461,3.272416,0.980312
13,14,Nixon,1995,Drama,6022,3.432082,0.940845
14,15,Cutthroat Island,1995,Action|Adventure|Romance,2910,2.721993,1.084532

In [182]:
movies.to_csv('./movielens/movies_all.csv')

In [6]:
movies_new = pd.DataFrame.copy(movies)
movies_new.tail(10)

,movieId,title,year,genres,n_users,rating_mean,rating_std
27268,131241,Ants in the Pants,2000,Comedy|Romance,1,4.0,0.0
27269,131243,Werner - Gekotzt wird später,2003,Animation|Comedy,1,4.0,0.0
27270,131248,Brother Bear 2,2006,Adventure|Animation|Children|Comedy|Fantasy,1,4.0,0.0
27271,131250,No More School,2000,Comedy,1,4.0,0.0
27272,131252,Forklift Driver Klaus: The First Day on the Job,2001,Comedy|Horror,1,4.0,0.0
27273,131254,Kein Bund für's Leben,2007,Comedy,1,4.0,0.0
27274,131256,"Feuer, Eis & Dosenbier",2002,Comedy,1,4.0,0.0
27275,131258,The Pirates,2014,Adventure,1,2.5,0.0
27276,131260,Rentun Ruusu,2001,(no genres listed),1,3.0,0.0
27277,131262,Innocence,2014,Adventure|Fantasy|Horror,1,4.0,0.0

In [7]:
movies_new.genres = movies_new.genres.str.split(pat='|')

In [8]:
movies_new.head(10)

,movieId,title,year,genres,n_users,rating_mean,rating_std
0,1,Toy Story,1995,"[Adventure, Animation, Children, Comedy, Fantasy]",49695,3.921240,0.889012
1,2,Jumanji,1995,"[Adventure, Children, Fantasy]",22243,3.211977,0.951150
2,3,Grumpier Old Men,1995,"[Comedy, Romance]",12735,3.151040,1.006642
3,4,Waiting to Exhale,1995,"[Comedy, Drama, Romance]",2756,2.861393,1.095702
4,5,Father of the Bride Part II,1995,[Comedy],12161,3.064592,0.982140
5,6,Heat,1995,"[Action, Crime, Thriller]",23899,3.834930,0.880468
6,7,Sabrina,1995,"[Comedy, Romance]",12961,3.366484,0.955883
7,8,Tom and Huck,1995,"[Adventure, Children]",1415,3.142049,0.966353
8,9,Sudden Death,1995,[Action],3960,3.004924,0.960203
9,10,GoldenEye,1995,"[Action, Adventure, Thriller]",29005,3.430029,0.859035

In [9]:
movies.head(10)

,movieId,title,year,genres,n_users,rating_mean,rating_std
0,1,Toy Story,1995,Adventure|Animation|Children|Comedy|Fantasy,49695,3.921240,0.889012
1,2,Jumanji,1995,Adventure|Children|Fantasy,22243,3.211977,0.951150
2,3,Grumpier Old Men,1995,Comedy|Romance,12735,3.151040,1.006642
3,4,Waiting to Exhale,1995,Comedy|Drama|Romance,2756,2.861393,1.095702
4,5,Father of the Bride Part II,1995,Comedy,12161,3.064592,0.982140
5,6,Heat,1995,Action|Crime|Thriller,23899,3.834930,0.880468
6,7,Sabrina,1995,Comedy|Romance,12961,3.366484,0.955883
7,8,Tom and Huck,1995,Adventure|Children,1415,3.142049,0.966353
8,9,Sudden Death,1995,Action,3960,3.004924,0.960203
9,10,GoldenEye,1995,Action|Adventure|Thriller,29005,3.430029,0.859035

In [10]:
movies_genres = dict()

In [20]:
for index, row in movies_new.iterrows():
    for genre in row['genres']:
        if (not(genre in movies_genres)):
            movies_genres[genre] = []
        movies_genres[genre].append(index)

In [22]:
for key, value in movies_genres.items():
    movies.iloc[value].to_csv(key + '.csv')

In [25]:
movies_drama = pd.read_csv('./movie_genres/Drama.csv')
movies_drama = movies_drama.drop('Unnamed: 0', axis=1)
print(movies_drama.shape)
movies_drama.head(15)

(13344, 7)

,movieId,title,year,genres,n_users,rating_mean,rating_std
0,4,Waiting to Exhale,1995,Comedy|Drama|Romance,2756,2.861393,1.095702
1,11,"American President, The",1995,Comedy|Drama|Romance,18162,3.667713,0.895807
2,14,Nixon,1995,Drama,6022,3.432082,0.940845
3,16,Casino,1995,Crime|Drama,17394,3.787455,0.863681
4,17,Sense and Sensibility,1995,Drama|Romance,20667,3.968573,0.951585
5,20,Money Train,1995,Action|Comedy|Crime|Drama|Thriller,4084,2.880754,0.930137
6,22,Copycat,1995,Crime|Drama|Horror|Mystery|Thriller,9928,3.319400,0.921065
7,24,Powder,1995,Drama|Sci-Fi,7971,3.199849,1.048937
8,25,Leaving Las Vegas,1995,Drama|Romance,21553,3.689510,1.034432
9,26,Othello,1995,Drama,2755,3.628857,0.925660
10,27,Now and Then,1995,Children|Drama,1642,3.413520,0.937641
11,28,Persuasion,1995,Drama|Romance,3154,4.057546,0.882361
12,29,"City of Lost Children, The (Cité des enfants p...",1995,Adventure|Drama|Fantasy|Mystery|Sci-Fi,8520,3.952230,0.975643
13,30,Shanghai Triad (Yao a yao yao dao waipo qiao),1995,Crime|Drama,1281,3.633880,0.977397
14,31,Dangerous Minds,1995,Drama,9435,3.250344,0.935127

In [24]:
avengers = list()
for index, row in movies.iterrows():
    if ('Avengers' in row['title']):
        avengers.append(index)
movies.iloc[avengers]

,movieId,title,year,genres,n_users,rating_mean,rating_std
2069,2153,"Avengers, The",1998,Action|Adventure,2684,2.078800,1.039400
10872,44020,Ultimate Avengers,2006,Action|Animation|Children|Sci-Fi,30,3.166667,0.758098
17874,89745,"Avengers, The",2012,Action|Adventure|Sci-Fi|IMAX,4959,3.949486,0.899397
23096,110132,Avengers Confidential: Black Widow & Punisher,2014,Action|Animation|Sci-Fi,11,2.772727,0.786245
24424,115727,Crippled Avengers (Can que) (Return of the 5 D...,1981,Action|Adventure,4,3.375000,0.946485